# Generated by Django 4.2.4 on 2023-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='haberSehir',
            field=models.CharField(default=1, max_length=50, verbose_name='Haberin Şehiri'),
            preserve_default=False,
        ),
    ]
