# Generated by Django 4.2.4 on 2023-10-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0003_haber_habersaati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Haber Başlık'),
        ),
    ]
