# Generated by Django 4.2.4 on 2023-10-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0005_magazingundem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biyografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='Ünlü İsmi')),
                ('resim', models.ImageField(upload_to=None, verbose_name='Ünlü Resim')),
                ('dogumTarihi', models.DateTimeField(verbose_name='Doğum Tarihi')),
                ('dogumYeri', models.CharField(max_length=50, verbose_name='Doğum Yeri')),
                ('meslek', models.CharField(max_length=50, verbose_name='Meslek')),
                ('biyografi', models.TextField(verbose_name='Biyografi')),
            ],
        ),
        migrations.DeleteModel(
            name='magazinGundem',
        ),
    ]
