# Generated by Django 4.2.4 on 2023-10-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0006_biyografi_delete_magazingundem'),
    ]

    operations = [
        migrations.AddField(
            model_name='biyografi',
            name='unluKategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haber.kategori', verbose_name='Ünlü Kategori'),
        ),
    ]
