# Generated by Django 4.2.4 on 2023-10-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0007_biyografi_unlukategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biyografi',
            name='dogumTarihi',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
    ]
