# Generated by Django 4.2.4 on 2023-10-14 14:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0008_alter_biyografi_dogumtarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biyografi',
            name='biyografi',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
